// ps5-homebrew-ui - Every component of the library in one include.
// Copyright (C) 2026 BlackBearReloaded
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Include this, or only the headers of the components you use. The guide is
// docs/COMPONENTS.md; each header starts with a usage example.

#pragma once

#include "ui/kit/ui/components/accordion.hpp"
#include "ui/kit/ui/components/action_glyph.hpp"
#include "ui/kit/ui/components/badge.hpp"
#include "ui/kit/ui/components/banner.hpp"
#include "ui/kit/ui/components/breadcrumb.hpp"
#include "ui/kit/ui/components/button.hpp"
#include "ui/kit/ui/components/button_group.hpp"
#include "ui/kit/ui/components/calendar.hpp"
#include "ui/kit/ui/components/card.hpp"
#include "ui/kit/ui/components/carousel.hpp"
#include "ui/kit/ui/components/chart.hpp"
#include "ui/kit/ui/components/choice.hpp"
#include "ui/kit/ui/components/choice_group.hpp"
#include "ui/kit/ui/components/coach_mark.hpp"
#include "ui/kit/ui/components/color_picker.hpp"
#include "ui/kit/ui/components/component.hpp"
#include "ui/kit/ui/components/counter.hpp"
#include "ui/kit/ui/components/data_common.hpp"
#include "ui/kit/ui/components/detail_list.hpp"
#include "ui/kit/ui/components/dialog.hpp"
#include "ui/kit/ui/components/focus_frame.hpp"
#include "ui/kit/ui/components/focus_group.hpp"
#include "ui/kit/ui/components/form.hpp"
#include "ui/kit/ui/components/grid.hpp"
#include "ui/kit/ui/components/hold_button.hpp"
#include "ui/kit/ui/components/hud.hpp"
#include "ui/kit/ui/components/image_viewer.hpp"
#include "ui/kit/ui/components/input_prompt.hpp"
#include "ui/kit/ui/components/inventory_grid.hpp"
#include "ui/kit/ui/components/jump_bar.hpp"
#include "ui/kit/ui/components/key_binder.hpp"
#include "ui/kit/ui/components/keyboard.hpp"
#include "ui/kit/ui/components/layout.hpp"
#include "ui/kit/ui/components/list.hpp"
#include "ui/kit/ui/components/loading_screen.hpp"
#include "ui/kit/ui/components/media_controls.hpp"
#include "ui/kit/ui/components/menu.hpp"
#include "ui/kit/ui/components/node_map.hpp"
#include "ui/kit/ui/components/notification.hpp"
#include "ui/kit/ui/components/notification_bell.hpp"
#include "ui/kit/ui/components/notification_center.hpp"
#include "ui/kit/ui/components/overlay.hpp"
#include "ui/kit/ui/components/page_dots.hpp"
#include "ui/kit/ui/components/pause_menu.hpp"
#include "ui/kit/ui/components/pin_entry.hpp"
#include "ui/kit/ui/components/profile_picker.hpp"
#include "ui/kit/ui/components/progress.hpp"
#include "ui/kit/ui/components/quick_action.hpp"
#include "ui/kit/ui/components/radial.hpp"
#include "ui/kit/ui/components/range_slider.hpp"
#include "ui/kit/ui/components/rating.hpp"
#include "ui/kit/ui/components/scroll_area.hpp"
#include "ui/kit/ui/components/search_field.hpp"
#include "ui/kit/ui/components/select.hpp"
#include "ui/kit/ui/components/sheet.hpp"
#include "ui/kit/ui/components/sidenav.hpp"
#include "ui/kit/ui/components/skeleton.hpp"
#include "ui/kit/ui/components/split_view.hpp"
#include "ui/kit/ui/components/stat.hpp"
#include "ui/kit/ui/components/status.hpp"
#include "ui/kit/ui/components/stepper.hpp"
#include "ui/kit/ui/components/surface.hpp"
#include "ui/kit/ui/components/table.hpp"
#include "ui/kit/ui/components/tabs.hpp"
#include "ui/kit/ui/components/tag_select.hpp"
#include "ui/kit/ui/components/text_field.hpp"
#include "ui/kit/ui/components/text_view.hpp"
#include "ui/kit/ui/components/timeline.hpp"
#include "ui/kit/ui/components/toast.hpp"
#include "ui/kit/ui/components/tooltip.hpp"
#include "ui/kit/ui/components/transition.hpp"
#include "ui/kit/ui/components/tree.hpp"
#include "ui/kit/ui/components/unlock_popup.hpp"
#include "ui/kit/ui/components/wheel_picker.hpp"
#include "ui/kit/ui/components/wizard.hpp"
