#!/usr/bin/env bash
# Accord - turn the pinned CA bundle into a C++ source the artifacts carry (T3.1).
#
# Embedding beats shipping a file. The daemon is a bare payload: it has no
# package, no asset directory and no promise that /data/accord/ exists on the
# console, while the title would have to carry a copy through the .ffpkg for a
# client the daemon is the one that uses. A raw string in the binary works
# everywhere, and the bundle's own header says which extraction it is.
#
#   tools/embed-cacert.sh <out.cpp>
#
# The caller picks the path -- each build has its own object directory -- and
# this script decides the contents, so the host tests, the daemon and anything
# later all carry byte-identical roots. The generated file is build output:
# build/ is gitignored, as is third_party/cacert/ that it comes from.

set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
out="${1:?usage: tools/embed-cacert.sh <out.cpp>}"

bundle="$root/third_party/cacert/cacert.pem"
if [ ! -f "$bundle" ]; then
    printf 'missing %s: run tools/fetch-cacert.sh\n' "$bundle" >&2
    exit 2
fi

# The provenance goes into the generated file rather than only into
# THIRD_PARTY.md: the binary is the thing that gets copied around, and this is
# what tells whoever finds it which roots it trusts.
sha=$(shasum -a 256 "$bundle" | cut -d' ' -f1)
as_of=$(sed -n 's/^## Certificate data from Mozilla as of: //p' "$bundle" | head -1)
count=$(grep -c '^-----BEGIN CERTIFICATE-----$' "$bundle" || true)

mkdir -p -- "$(dirname -- "$out")"

{
    printf '/*\n'
    printf ' * Accord - the pinned CA bundle, generated by tools/embed-cacert.sh.\n'
    printf ' * SPDX-License-Identifier: GPL-3.0-or-later\n'
    printf ' *\n'
    printf ' * Do not edit: run tools/fetch-cacert.sh (which fetches the bundle) and\n'
    printf ' * tools/embed-cacert.sh (which writes this file) instead.\n'
    printf ' *\n'
    printf ' * Mozilla root certificates as curl publishes them, extraction of %s,\n' "$as_of"
    printf ' * %s certificates, sha256 %s.\n' "$count" "$sha"
    printf ' * Source and licence: https://curl.se/docs/caextract.html (see THIRD_PARTY.md).\n'
    printf ' */\n'
    printf '\n'
    printf '#include "platform/net/ca_bundle.hpp"\n'
    printf '\n'
    printf 'namespace accord::net\n'
    printf '{\n'
    printf 'namespace\n'
    printf '{\n'
    printf '// The file, comments and all: nothing here has to understand a certificate,\n'
    printf '// the TLS library parses the text. Byte for byte as it was published, except\n'
    printf '// that a backslash and a quote are escaped.\n'
    printf '//\n'
    printf '// It arrives as one literal per group of lines only so that no single source\n'
    printf '// line is unreadable; adjacent literals are one array to the compiler, and\n'
    printf '// sizeof below still counts the whole PEM. That whole PEM is past the length\n'
    printf '// C++ compilers must support, so this one file is built with\n'
    printf '// -Wno-overlength-strings (see the Makefile and tools/build-daemon-payload.sh):\n'
    printf '// the warning is about the text, which is exactly what was asked for.\n'
    printf 'const char kCaBundlePem[] =\n'
    awk '
    {
        text = $0
        gsub(/\\/, "\\\\", text)
        gsub(/"/, "\\\"", text)
        piece = "\"" text "\\n\""
        if (used + length(piece) + 1 > 60000) { printf "\n"; used = 0 }
        printf "%s ", piece
        used += length(piece) + 1
    }
    END { printf "\n" }
    ' "$bundle"
    printf ';\n'
    printf '} // namespace\n'
    printf '\n'
    printf 'std::string_view bundled_ca_pem()\n'
    printf '{\n'
    printf '    return std::string_view{kCaBundlePem, sizeof(kCaBundlePem) - 1};\n'
    printf '}\n'
    printf '} // namespace accord::net\n'
} >"$out"

printf '==> [cacert] %s: %s certificates, sha256 %s\n' "$out" "$count" "$sha"
