#!/usr/bin/env bash
# Accord - OpenGL link preparation for the console title.
#
# Two things the boilerplate harness needs before it can link the kit:
#
#   1. the linker group, third_party/ps5-opengl/libps5opengl-group.a. It is a
#      linker script rather than an archive: it pulls in libPS5OpenGL.a with the
#      unwinder and the C++ runtimes it needs, and re-exports the runtime entry
#      point, which is only reachable through the driver's dispatch table.
#   2. the AGC import stubs, copied into the payload SDK's target/lib. That
#      directory is both the shared-library link input and the harness's
#      --stub-dir, so a system module dropped in there is stubbed the same way
#      libScePad.so and libSceAudioOut.so already are.
#
# Run inside the builder container: the harness resolves these paths from the
# repository root, and no harness file is modified to make it work.
#
#   scripts/dev.sh bash tools/prepare-opengl.sh

set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
boilerplate="$root/third_party/ps5-native-app-boilerplate"
target_lib="$boilerplate/.deps/native/ps5-payload-sdk/target/lib"
group="$root/third_party/ps5-opengl/libps5opengl-group.a"

sdk=$(bash "$root/tools/fetch-opengl-sdk.sh")

for required in include/GL/glcorearb.h include/EGL/egl.h include/ps5_opengl_display.h \
    lib/libPS5OpenGL.a lib/libSceAgc.so lib/libSceAgcDriver.so; do
    [[ -f $sdk/$required ]] || {
        printf 'ps5-opengl SDK is missing %s: %s\n' "$required" "$sdk" >&2
        exit 2
    }
done

# The payload SDK carries the unwinder and the C++ runtimes the group links; on
# a fresh clone the harness has not downloaded it yet.
[[ -s $target_lib/libunwind.a ]] ||
    bash "$boilerplate/tools/setup-native-dependencies.sh" >/dev/null

compiler=$(command -v "${PS5_CLANG:-clang-18}" || command -v clang)
builtins=$("$compiler" --print-resource-dir)/lib/linux/libclang_rt.builtins-x86_64.a
for library in "$target_lib/libunwind.a" "$target_lib/libc++abi.a" \
    "$target_lib/libc++.a" "$builtins"; do
    [[ -s $library ]] || {
        printf 'missing link input: %s\n' "$library" >&2
        exit 2
    }
done

mkdir -p -- "$target_lib"
for stub in libSceAgc.so libSceAgcDriver.so; do
    cmp -s "$sdk/lib/$stub" "$target_lib/$stub" || cp -- "$sdk/lib/$stub" "$target_lib/$stub"
done

# Rewritten only when it would differ, so a rebuild does not relink for nothing.
# Not committed: *.a is ignored, and this file is regenerated from the SDK path.
tmp="$group.tmp"
{
    printf '/* Generated by tools/prepare-opengl.sh; do not edit. */\n'
    printf 'SEARCH_DIR("%s")\n' "$sdk/lib" "$target_lib"
    printf 'EXTERN(ps5_agc_gate2_run)\n'
    printf 'GROUP (\n'
    printf '  "%s"\n' "$sdk/lib/libPS5OpenGL.a" "$target_lib/libunwind.a" \
        "$target_lib/libc++abi.a" "$target_lib/libc++.a" "$builtins"
    printf ')\n'
    # libunwind finds the unwind tables through the bounds of .eh_frame. The
    # harness's ps5-pie.ld does not define them (ps5-opengl's own native-app
    # script, and the ps5-homebrew-ui harness, carry the same four as PROVIDE),
    # so this input script defines them: a script given as an input may assign
    # symbols, and ADDR() resolves once the sections are laid out.
    printf '__eh_frame_start = ADDR(.eh_frame);\n'
    printf '__eh_frame_end = ADDR(.eh_frame) + SIZEOF(.eh_frame);\n'
    printf '__eh_frame_hdr_start = ADDR(.eh_frame_hdr);\n'
    printf '__eh_frame_hdr_end = ADDR(.eh_frame_hdr) + SIZEOF(.eh_frame_hdr);\n'
} > "$tmp"
if cmp -s "$tmp" "$group"; then
    rm -f -- "$tmp"
else
    mv -- "$tmp" "$group"
fi

manifest=$(sha256sum "$sdk/manifest.sha256" | cut -d' ' -f1)
printf 'OpenGL SDK: %s\nOpenGL SDK manifest: %s\nLink group: %s\n' \
    "$sdk" "$manifest" "$group"
